sudo: required

services:
    - docker

language: c++

install: docker pull debian:stretch

script:
    - mkdir build
    - |
        docker run -v "$PWD:/workspace" -w /workspace/build debian:stretch /bin/bash -ex -c '
            apt -q update
            DEBIAN_FRONTEND=noninteractive apt -qqy install cmake g++-mingw-w64-x86-64
            cmake \
                -DCMAKE_SYSTEM_NAME=Windows \
                -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
                -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
                -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
                -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
                -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
                -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                /workspace
            make VERBOSE=1
        '
