sudo: required

services:
    - docker

language: c++

install: docker pull debian:stretch

script:
    - mkdir build
    - |
        docker run -v "$PWD:/workspace" -w /workspace/build debian:stretch /bin/bash -e -c '
            function travis_fold {
                local name="$1"; shift
                echo "travis_fold:start:$name"
                echo "\$ $@"
                "$@"
                echo "travis_fold:end:$name"
            }

            travis_fold docker-apt-update apt -q update

            DEBIAN_FRONTEND=noninteractive travis_fold docker-apt-install apt -qqy install cmake g++-mingw-w64-x86-64

            travis_fold docker-cmake cmake \
                -DCMAKE_SYSTEM_NAME=Windows \
                -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
                -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres \
                -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
                -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
                -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
                -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                /workspace

            travis_fold docker-make make VERBOSE=1
        '
